import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const obviouslyVariable = localFont({
  subsets: ["latin"],
  src: "../../fonts/ObviouslyNarrow-Bold.otf",
  variable: "--font-obviously",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${obviouslyVariable.variable} ${inter.className} bg-purple-100 text-neutral-800 antialiased relative`}
      >
        <div className="fixed inset-0 pointer-events-none z-[-50]">
          {[1, 2, 3, 4, 5].map((index) => (
            <div
              key={index}
              className="absolute top-0 bottom-0 w-px bg-purple-700/10"
              style={{ left: `${(index * 100) / 6}%` }}
            />
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
